
on:
  workflow_dispatch:
  push:
    branches:
      - main
name: Terraform
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Apply
      run: terraform apply -auto-approve -no-color
